import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.resume': 'My Resume',
    'nav.about': 'About Me',
    'nav.projects': 'My Projects',
    'nav.contact': 'Contact me',
    'hero.greeting': "👋 Hi, I'm",
    'hero.title': 'Full Stack Web Developer',
    'hero.description': 'Crafting interactive, scalable, and human-centered digital experiences',
    'hero.viewWork': 'View My Work',
    'hero.connect': "Let's Connect",
    'about.title': 'About Me',
    'about.journey': 'My Journey',
    'about.journeyText': 'Trained at Le Wagon Cape Town, I transformed my passion for technology into expertise in building modern, full-stack web applications. Every line of code I write is driven by curiosity, innovation, and the desire to create seamless digital experiences.',
    'about.strengths': 'Key Strengths',
    'about.strength1': 'Modern UI/UX Design',
    'about.strength2': 'Full-Stack Development',
    'about.strength3': 'Scalable Architecture',
    'about.timeline.experience.heading': 'Professional Experience',
    'about.timeline.education.heading': 'Education & Certifications',
    'about.timeline.experience.istanbul.period': 'Jun. 2023 – Sept. 2023',
    'about.timeline.experience.istanbul.title': 'Electrical Installation Assistant',
    'about.timeline.experience.istanbul.role': 'Sahip Camp · Istanbul, Turkey',
    'about.timeline.experience.istanbul.description': 'Installed and maintained electrical systems across the camp, ensuring safety compliance and reliable operations in a high-demand environment.',
    'about.timeline.experience.cybercafe.period': 'Jul. 2021 – Oct. 2021',
    'about.timeline.experience.cybercafe.title': 'Cybercafe Operations Manager',
    'about.timeline.experience.cybercafe.role': 'Cybercafe Leon Mba · Port-Gentil',
    'about.timeline.experience.cybercafe.description': 'Oversaw day-to-day operations, trained staff on systems and customer support, maintained the website for better accessibility, and managed cash flow.',
    'about.timeline.experience.seeg.period': 'Jul. 2015 – Oct. 2015',
    'about.timeline.experience.seeg.title': 'Service Agent (EDAN System)',
    'about.timeline.experience.seeg.role': 'EPS Prestation · Port-Gentil',
    'about.timeline.experience.seeg.description': 'Assembled and installed electrical networks and single-phase meters for SEEG, contributing to reliable energy distribution.',
    'about.timeline.education.lewagon.period': 'Oct. 2024 – Dec. 2024',
    'about.timeline.education.lewagon.title': 'Full-Stack Web Developer',
    'about.timeline.education.lewagon.role': 'Le Wagon · Cape Town, South Africa',
    'about.timeline.education.lewagon.description': '9-week intensive bootcamp covering modern front-end, back-end, databases, and deployment with a product-driven mindset.',
    'about.timeline.education.istanbul.period': 'Jan. 2023 – Mar. 2023',
    'about.timeline.education.istanbul.title': 'Turkish Language Program',
    'about.timeline.education.istanbul.role': 'Istanbul Kent Üniversitesi · Istanbul, Turkey',
    'about.timeline.education.istanbul.description': 'Completed immersive language coursework to strengthen communication and cultural fluency for professional opportunities.',
    'about.timeline.education.duzce.period': 'Feb. 2022 – Oct. 2022',
    'about.timeline.education.duzce.title': 'Turkish Language Certification',
    'about.timeline.education.duzce.role': 'Düzce Üniversitesi · Düzce, Turkey',
    'about.timeline.education.duzce.description': 'Expanded Turkish language mastery with advanced grammar, conversation, and professional use cases.',
    'about.timeline.education.lycee.period': 'Oct. 2020 – Jul. 2021',
    'about.timeline.education.lycee.title': 'Mechanical Engineering Track Diploma',
    'about.timeline.education.lycee.role': 'Jean Fidèle Otando Technical High School · Port-Gentil',
    'about.timeline.education.lycee.description': 'Specialized in industrial maintenance, combining theoretical training with practical workshops and safety protocols.',
    'about.stats.title': 'Core Stack Focus',
    'about.stats.caption': 'Weekly time investment across key disciplines',
    'about.softskills.communication': 'Client communication',
    'about.softskills.leadership': 'Technical leadership',
    'about.softskills.problemSolving': 'Creative problem-solving',
    'about.highlight.title': 'Full stack artisan',
    'about.highlight.subtitle': 'Merging design, engineering, and strategy for ambitious brands.',
    'projects.title': 'Featured Projects',
    'projects.allTitle': 'All Projects',
    'projects.viewGithub': 'View All on GitHub',
    'projects.seeDetails': 'See Details',
    'skills.title': 'Tech Stack',
    'experience.title': 'Experience & Education',
    'experience.bootcamp': 'Le Wagon Bootcamp - Cape Town',
    'experience.bootcampDesc': 'Intensive full-stack web development program covering modern frameworks, databases, and deployment.',
    'experience.growth': 'Post-Graduation Growth',
    'experience.growthDesc': 'Built real-world applications, contributed to open-source projects, and continuously expanded my tech stack.',
    'contact.title': 'Get In Touch',
    'contact.description': "Have a project in mind? Let's build something amazing together!",
    'contact.tagline': 'Let’s collaborate',
    'contact.form.title': 'Tell me about your vision',
    'contact.form.subtitle': 'Share your goals, timeline, or challenges and I will come back with concrete next steps.',
    'contact.name': 'Your Name',
    'contact.email': 'Your Email',
    'contact.message': 'Your Message',
    'contact.send': 'Send Message',
    'contact.info': 'Contact Information',
    'contact.availability.title': 'Availability',
    'contact.availability.status': 'Open to collaborations',
    'contact.availability.description': 'I’m partnering with teams on full-stack web experiences, dashboards, and product prototypes.',
    'contact.availability.responseLabel': 'Response time',
    'contact.availability.responseValue': '< 24h',
    'contact.availability.timezoneLabel': 'Timezone',
    'contact.availability.timezoneValue': 'GMT+1 (West Africa)',
    'contact.availability.languageLabel': 'Languages',
    'contact.availability.languageValue': 'French · English · Turkish',
    'contact.channels.whatsapp': 'WhatsApp / Phone',
    'contact.channels.email': 'Email',
    'contact.channels.location': 'Location',
    'contact.cta.meeting': 'Schedule a call',
    'contact.cta.email': 'Write me directly',
    'contact.location.value': 'Port-Gentil, Gabon',
    'footer.rights': '© 2025 Revyll OGANDAGA | Built with Vision',
    'modal.contact.title': "Let's Connect",
    'modal.contact.description': "Fill out the form below and I'll get back to you as soon as possible.",
    'modal.resume.title': 'My Resumes',
    'modal.resume.description': 'Select a resume to view',
  },
  fr: {
    'nav.resume': 'Mon CV',
    'nav.about': 'À Propos',
    'nav.projects': 'Mes Projets',
    'nav.contact': 'Contact',
    'hero.greeting': "👋 Salut, je suis",
    'hero.title': 'Développeur Web Full Stack',
    'hero.description': 'Création d\'expériences numériques interactives, évolutives et centrées sur l\'humain',
    'hero.viewWork': 'Voir Mon Travail',
    'hero.connect': 'Connectons-nous',
    'about.title': 'À Propos de Moi',
    'about.journey': 'Mon Parcours',
    'about.journeyText': 'Formé au Wagon Cape Town, j\'ai transformé ma passion pour la technologie en expertise dans la construction d\'applications web modernes et complètes. Chaque ligne de code que j\'écris est motivée par la curiosité, l\'innovation et le désir de créer des expériences numériques fluides.',
    'about.strengths': 'Points Forts',
    'about.strength1': 'Design UI/UX Moderne',
    'about.strength2': 'Développement Full-Stack',
    'about.strength3': 'Architecture Évolutive',
    'about.timeline.experience.heading': 'Expérience Professionnelle',
    'about.timeline.education.heading': 'Formations & Certifications',
    'about.timeline.experience.istanbul.period': 'Juin 2023 – Sept. 2023',
    'about.timeline.experience.istanbul.title': 'Assistant Installation Électrique',
    'about.timeline.experience.istanbul.role': 'Sahip Camp · Istanbul, Turquie',
    'about.timeline.experience.istanbul.description': 'Installation et maintenance des systèmes électriques du camp en garantissant conformité et fiabilité dans un contexte exigeant.',
    'about.timeline.experience.cybercafe.period': 'Juil. 2021 – Oct. 2021',
    'about.timeline.experience.cybercafe.title': 'Responsable Cybercafé',
    'about.timeline.experience.cybercafe.role': 'Cybercafé Leon Mba · Port-Gentil',
    'about.timeline.experience.cybercafe.description': 'Pilotage des opérations quotidiennes, formation du personnel, optimisation du site web pour l’accessibilité et gestion de la trésorerie.',
    'about.timeline.experience.seeg.period': 'Juil. 2015 – Oct. 2015',
    'about.timeline.experience.seeg.title': 'Agent Service (Système EDAN)',
    'about.timeline.experience.seeg.role': 'EPS Prestation · Port-Gentil',
    'about.timeline.experience.seeg.description': 'Assemblage et installation de réseaux électriques et de compteurs monophasés pour la SEEG.',
    'about.timeline.education.lewagon.period': 'Oct. 2024 – Déc. 2024',
    'about.timeline.education.lewagon.title': 'Développeur Web Full-Stack',
    'about.timeline.education.lewagon.role': 'Le Wagon · Cape Town, Afrique du Sud',
    'about.timeline.education.lewagon.description': 'Bootcamp intensif de 9 semaines couvrant front-end, back-end, bases de données et déploiement avec une approche produit.',
    'about.timeline.education.istanbul.period': 'Jan. 2023 – Mar. 2023',
    'about.timeline.education.istanbul.title': 'Programme de Langue Turque',
    'about.timeline.education.istanbul.role': 'Istanbul Kent Üniversitesi · Istanbul, Turquie',
    'about.timeline.education.istanbul.description': 'Cours immersifs pour renforcer la communication et la compréhension culturelle dans un contexte professionnel.',
    'about.timeline.education.duzce.period': 'Fév. 2022 – Oct. 2022',
    'about.timeline.education.duzce.title': 'Certification Langue Turque',
    'about.timeline.education.duzce.role': 'Düzce Üniversitesi · Düzce, Turquie',
    'about.timeline.education.duzce.description': 'Approfondissement de la maîtrise du turc avec grammaire avancée, conversation et cas d’usage professionnels.',
    'about.timeline.education.lycee.period': 'Oct. 2020 – Juil. 2021',
    'about.timeline.education.lycee.title': 'Baccalauréat Technique Génie Mécanique',
    'about.timeline.education.lycee.role': 'Lycée Technique Jean Fidèle Otando · Port-Gentil',
    'about.timeline.education.lycee.description': 'Spécialisation en maintenance industrielle alliant théorie, ateliers pratiques et protocoles de sécurité.',
    'about.stats.title': 'Focalisation du Stack',
    'about.stats.caption': 'Temps hebdomadaire investi sur les disciplines clés',
    'about.softskills.communication': 'Communication client',
    'about.softskills.leadership': 'Leadership technique',
    'about.softskills.problemSolving': 'Résolution créative',
    'about.highlight.title': 'Artisan full stack',
    'about.highlight.subtitle': 'Allier design, ingénierie et stratégie pour des marques ambitieuses.',
    'projects.title': 'Projets en Vedette',
    'projects.allTitle': 'Tous les Projets',
    'projects.viewGithub': 'Voir Tout sur GitHub',
    'projects.seeDetails': 'Voir Détails',
    'skills.title': 'Stack Technique',
    'experience.title': 'Expérience & Formation',
    'experience.bootcamp': 'Le Wagon Bootcamp - Cape Town',
    'experience.bootcampDesc': 'Programme intensif de développement web full-stack couvrant les frameworks modernes, les bases de données et le déploiement.',
    'experience.growth': 'Croissance Post-Diplôme',
    'experience.growthDesc': 'Construction d\'applications réelles, contribution à des projets open-source et expansion continue de ma stack technique.',
    'contact.title': 'Contactez-Moi',
    'contact.description': 'Vous avez un projet en tête ? Construisons quelque chose d\'incroyable ensemble !',
    'contact.tagline': 'Créons ensemble',
    'contact.form.title': 'Parlez-moi de votre vision',
    'contact.form.subtitle': 'Partagez vos objectifs, vos délais ou vos défis et je reviens vers vous avec des pistes concrètes.',
    'contact.name': 'Votre Nom',
    'contact.email': 'Votre Email',
    'contact.message': 'Votre Message',
    'contact.send': 'Envoyer',
    'contact.info': 'Informations de Contact',
    'contact.availability.title': 'Disponibilité',
    'contact.availability.status': 'Ouvert aux collaborations',
    'contact.availability.description': 'J’accompagne les équipes sur des expériences web full-stack, dashboards et prototypes produits.',
    'contact.availability.responseLabel': 'Temps de réponse',
    'contact.availability.responseValue': '< 24h',
    'contact.availability.timezoneLabel': 'Fuseau horaire',
    'contact.availability.timezoneValue': 'GMT+1 (Afrique de l’Ouest)',
    'contact.availability.languageLabel': 'Langues',
    'contact.availability.languageValue': 'Français · Anglais · Turc',
    'contact.channels.whatsapp': 'WhatsApp / Téléphone',
    'contact.channels.email': 'Email',
    'contact.channels.location': 'Localisation',
    'contact.cta.meeting': 'Planifier un appel',
    'contact.cta.email': 'M’écrire directement',
    'contact.location.value': 'Port-Gentil, Gabon',
    'footer.rights': '© 2025 Revyll OGANDAGA | Construit avec Vision',
    'modal.contact.title': 'Connectons-nous',
    'modal.contact.description': 'Remplissez le formulaire ci-dessous et je vous répondrai dès que possible.',
    'modal.resume.title': 'Mes CV',
    'modal.resume.description': 'Sélectionnez un CV à consulter',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
